const feeds={vietnam:'https://news.google.com/rss?hl=vi&gl=VN&ceid=VN:vi',world:'https://news.google.com/rss?hl=en&gl=US&ceid=US:en'};
const proxy='https://api.rss2json.com/v1/api.json?rss_url=';
const escapeHtml=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const stripHtml=value=>String(value||'').replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim();
const formatDate=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?'Mới cập nhật':date.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});};
async function loadFeed(key,targetId){const target=document.getElementById(targetId);target.innerHTML='<div class="loading">Đang tải tin<span>...</span></div>';try{const response=await fetch(proxy+encodeURIComponent(feeds[key]),{cache:'no-store'});if(!response.ok)throw new Error('feed');const data=await response.json();const items=(data.items||[]).slice(0,10);if(!items.length)throw new Error('empty');target.innerHTML=items.map((item,index)=>{const image=item.thumbnail||item.enclosure?.link||'';const imageMarkup=image?`<img class="news-thumb" src="${escapeHtml(image)}" alt="" loading="lazy" onerror="this.remove()">`:'';return `<a class="news-item" href="${escapeHtml(item.link)}" target="_blank" rel="noopener"><span class="news-rank">${String(index+1).padStart(2,'0')}</span><span class="news-content"><h3>${escapeHtml(stripHtml(item.title))}</h3><span class="news-meta">${escapeHtml(item.author||data.feed?.title||'Nguồn tin')} · ${formatDate(item.pubDate)}</span></span>${imageMarkup}<span class="news-arrow" aria-hidden="true">↗</span></a>`;}).join('');}catch(error){target.innerHTML='<div class="error">Không thể tải tin lúc này. <button type="button" data-retry="'+key+'">Thử lại</button></div>';}}
function loadAll(){loadFeed('vietnam','vietnamNews');loadFeed('world','worldNews');}
document.getElementById('refreshButton').addEventListener('click',loadAll);
document.addEventListener('click',event=>{const button=event.target.closest('[data-retry]');if(button)loadFeed(button.dataset.retry,button.dataset.retry==='vietnam'?'vietnamNews':'worldNews');});
document.getElementById('year').textContent=new Date().getFullYear();loadAll();
